# [[database]]
# Name = 'demo'
# Provider = 'mysql'
# DBName = 'demo'
# URL = 'mysql://user:pass@127.0.0.1:${port}/db'
# Commands = [
#   # ssh -f user@ssh.example.com -L 3307:mysql.example.com:3306 -N
#   # pass: printf %s 'FkbIM%51$EG@mt82hqe%' | jq -sRr @uri
#   { Command = 'ssh -tt lm -L ${port}:remotehost:3306', WaitForPort = '${port}' }
# ]
[application]
DefaultPageSize = 50
DisableSidebar = false
SidebarOverlay = false
